"""
RAG pipeline — public version (state-level only).
Adapted from src/rag/rag_pipeline.py in backend-tia.
"""
import logging
import time
from dataclasses import dataclass
from neo4j import Driver

from .retriever import Retriever
from .context_builder import build_state_context
from .prompt_templates import STATE_ANALYSIS, STATE_ANALYSIS_EN
from .llm_client import get_llm_client
from .topic_gate import is_education_related

logger = logging.getLogger(__name__)

# Hardcoded fallback messages — never generated by the LLM.
_OFFTOPIC_FALLBACK = {
    "pt-BR": (
        "Sou a **T.I.A**, assistente de inteligência educacional. "
        "Só posso responder perguntas sobre **educação brasileira**, "
        "IDEB, escolas e temas relacionados.\n\n"
        "Me pergunte algo sobre educação! 🎓"
    ),
    "en": (
        "I'm **T.I.A**, an educational intelligence assistant. "
        "I can only answer questions about **Brazilian education**, "
        "IDEB, schools, and related topics.\n\n"
        "Please ask me something about education! 🎓"
    ),
}


@dataclass
class RAGResponse:
    answer:       str
    context_len:  int = 0
    latency_ms:   int = 0
    model_used:   str = ""
    data_quality: str = "desconhecido"
    granularity:  str = "estado"


class RAGPipeline:
    def __init__(self, driver: Driver, database: str = "neo4j"):
        self._retriever = Retriever(driver, database=database)
        self._llm = get_llm_client()

    def ask_about_state(self, uf: str, question: str, language: str = "pt-BR") -> RAGResponse:
        t0 = time.time()

        # ── Topic gate: block off-topic before retriever/LLM ─────────────
        if not is_education_related(question):
            logger.info("topic_gate BLOCKED uf=%s question=%r", uf, question[:80])
            return RAGResponse(
                answer=_OFFTOPIC_FALLBACK.get(language, _OFFTOPIC_FALLBACK["pt-BR"]),
                latency_ms=int((time.time() - t0) * 1000),
                model_used="topic_gate",
                granularity="blocked",
            )

        ctx_dict = self._retriever.get_state_context(uf)
        if not ctx_dict:
            return RAGResponse(answer=f"Estado {uf} não encontrado.", granularity="estado")

        context_str = build_state_context(ctx_dict)
        template = STATE_ANALYSIS_EN if language == "en" else STATE_ANALYSIS
        answer = self._llm.ask(context_str, question, template, language=language)
        return RAGResponse(
            answer=answer,
            context_len=len(context_str),
            latency_ms=int((time.time() - t0) * 1000),
            model_used=type(self._llm).__name__,
            granularity="estado",
        )
